<a href="https://colab.research.google.com/github/ilyasa2002/Penjualan_Handphone/blob/main/UTS%20Machine%20Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [29]:
data = pd.read_csv("Flipkart.csv")
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [4]:
print(x)

[['OPPO' 'A53' 'Moonlight Black' ... '64 GB' 4.5 11990]
 ['OPPO' 'A53' 'Mint Cream' ... '64 GB' 4.5 11990]
 ['OPPO' 'A53' 'Moonlight Black' ... '128 GB' 4.3 13990]
 ...
 ['SAMSUNG' 'M52 5G' 'Icy Blue' ... '128 GB' 4.3 27239]
 ['SAMSUNG' 'M52 5G' 'Slate Black' ... '128 GB' 4.2 22989]
 ['SAMSUNG' 'M52 5G' 'Sky Blue' ... '128 GB' 4.2 20350]]


In [5]:
print(y)

[15990 15990 17990 ... 31489 22989 22595]


In [6]:
data.isnull().sum()

Brand               0
Model               0
Color               0
Memory             43
Storage            39
Rating            144
Selling Price       0
Original Price      0
dtype: int64

In [7]:
most_frequent_Memory = data["Memory"].mode()[0]

In [8]:
print (most_frequent_Memory)

4 GB


In [9]:
most_frequent_Storage = data["Storage"].mode()[0]

In [10]:
print (most_frequent_Storage)

64 GB


In [11]:
data["Memory"] = data["Memory"].fillna(most_frequent_Memory)

In [12]:
data.isnull().sum()

Brand               0
Model               0
Color               0
Memory              0
Storage            39
Rating            144
Selling Price       0
Original Price      0
dtype: int64

In [13]:
data["Storage"] = data["Storage"].fillna(most_frequent_Storage)

In [14]:
data.isnull().sum()

Brand               0
Model               0
Color               0
Memory              0
Storage             0
Rating            144
Selling Price       0
Original Price      0
dtype: int64

In [15]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
data['Rating'] = imputer.fit_transform(data[['Rating']])

In [16]:
print (data)

        Brand   Model            Color Memory Storage  Rating  Selling Price  \
0        OPPO     A53  Moonlight Black   4 GB   64 GB     4.5          11990   
1        OPPO     A53       Mint Cream   4 GB   64 GB     4.5          11990   
2        OPPO     A53  Moonlight Black   6 GB  128 GB     4.3          13990   
3        OPPO     A53       Mint Cream   6 GB  128 GB     4.3          13990   
4        OPPO     A53   Electric Black   4 GB   64 GB     4.5          11990   
...       ...     ...              ...    ...     ...     ...            ...   
3109  SAMSUNG  M52 5G    Blazing Black   6 GB  128 GB     4.3          25990   
3110  SAMSUNG  M52 5G         Icy Blue   6 GB  128 GB     4.3          25489   
3111  SAMSUNG  M52 5G         Icy Blue   8 GB  128 GB     4.3          27239   
3112  SAMSUNG  M52 5G      Slate Black   8 GB  128 GB     4.2          22989   
3113  SAMSUNG  M52 5G         Sky Blue   8 GB  128 GB     4.2          20350   

      Original Price  
0              1

In [17]:
data.isnull().sum()

Brand             0
Model             0
Color             0
Memory            0
Storage           0
Rating            0
Selling Price     0
Original Price    0
dtype: int64

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [19]:
print(x)

[[0.0 0.0 0.0 ... '64 GB' 4.5 11990]
 [0.0 0.0 0.0 ... '64 GB' 4.5 11990]
 [0.0 0.0 0.0 ... '128 GB' 4.3 13990]
 ...
 [0.0 0.0 0.0 ... '128 GB' 4.3 27239]
 [0.0 0.0 0.0 ... '128 GB' 4.2 22989]
 [0.0 0.0 0.0 ... '128 GB' 4.2 20350]]


In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [21]:
print (y)

[433 433 474 ... 623 547 544]


In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [23]:
print(x_train)

[[0.0 0.0 0.0 ... '64 GB' 4.4 19990]
 [0.0 0.0 0.0 ... '32 GB' 4.4 7199]
 [0.0 0.0 0.0 ... '64 GB' 4.4 32990]
 ...
 [0.0 0.0 0.0 ... '64 GB' 4.3 18599]
 [0.0 0.0 0.0 ... '64 GB' 4.3 18990]
 [0.0 0.0 0.0 ... '16 GB' 4.1 7139]]


In [24]:
print(x_test)

[[0.0 0.0 0.0 ... '64 GB' 4.5 9999]
 [0.0 0.0 0.0 ... '32 GB' 4.2 8299]
 [0.0 0.0 0.0 ... '32 GB' 4.4 14995]
 ...
 [0.0 0.0 0.0 ... '128 GB' 4.6 53990]
 [0.0 0.0 0.0 ... '16 GB' 4.3 8990]
 [0.0 0.0 0.0 ... '8 GB' 3.9 7999]]


In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
scaled_x_train = sc.fit_transform(x_train[:, :6])
scaled_x_test = sc.transform(x_test[:, :6])

In [26]:
print (scaled_x_train)

[[-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]
 ...
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]]


In [27]:
print (scaled_x_test)

[[-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]
 ...
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645  7.29055375 -0.04484711]
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645 -0.13716379 -0.04484711]
 [-0.20236793 -0.37770432 -0.20873269 -0.09653645  7.29055375 -0.04484711]]
